### PR TITLE
support curl, wget, perl timeout replacement, busybox timeout params

### LINKED ISSUE #15: Support running on OSX
OSX bash shell doesn't have a timeout command, but often (at least dev OSX machines) will have perl.  Can do:

    function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }

### PR DESCRIPTION
**Pull request by DukeyToo**
Will fix #15, #16, #5 .  

Adds command-line switches for busybox, and using `curl` and `wget` for more correct tests of http endpoints.  If `timeout` command is not found, then will attempt to use a `perl` replacement.

These are all changes I made for my own needs in orchestrating the startup and configuration of a bunch of docker containers.

### CODE REVIEW

**Comment by dakl** [comment]
👍

**Comment by dequis** [comment]
```
# sh wait-for-it.sh
wait-for-it.sh: line 67: syntax error: unexpected "(" (expecting "fi")
```

BusyBox v1.24.2 (from docker:latest image). This sucks since that part of the if isn't even executed, but I guess shells aren't infinitely forgiving when parsing

**Comment by eigood** [comment]
I'd first attempt to use /dev/tcp(or /dev/udp) in a redirect first, before attempting external programs.  There's the issue with not being able to set the timeout when doing it this way, however, that can be worked around by using a background process that sends a signal to the parent.

**Comment by jmagnusson** [comment]
`/dev/tcp` sounds like an interesting approach. @eigood Have you seen an implementation of this? Would be especially interesting to see HTTP status code parsing.

**Pull request closed without merging**
